spring.application.name: product-service

spring.data.mongodb:
  auto-index-creation: true
  host: localhost
  port: 27017
  database: product-db

server:
  port: 7001
  error.include-message: always

logging:
  level:
    root: INFO
    tech.maxjung: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

