spring.application.name: recommendation-service

spring.data.mongodb:
  auto-index-creation: true
  host: localhost
  port: 27017
  database: recommendation-db


server:
  port: 7002
  error.include-message: always

logging:
  level:
    root: INFO
    tech.maxjung: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG