spring.application.name: review-service

server:
  port: 7003
  error.include-message: always

# Use 'update' for automatic schema updates in development;
# set to 'none' in production to avoid unexpected schema changes.
# Use tools like Liquibase or Flyway for schema management.
spring.jpa.hibernate.ddl-auto: update
spring.jpa:
  show-sql: true

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000


logging:
  level:
    root: INFO
    tech.maxjung: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE